"use client";

import { useEffect, useState } from "react";
import { DashboardShell } from "../../components/DashboardShell";
import { api, getErrorMessage } from "../../lib/api";

type Wallet = { publicKey: string; network: string; balanceSol: number };

export default function CryptoPage() {
  const [wallet, setWallet] = useState<Wallet | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { api.get("/api/v1/user/solana-wallet").then((response) => setWallet(response.data.wallet)).catch((caught) => setError(getErrorMessage(caught))); }, []);
  async function createWallet() { setBusy(true); setError(""); try { const response = await api.post("/api/v1/user/solana-wallet"); setWallet({ ...response.data.wallet, balanceSol: 0 }); } catch (caught) { setError(getErrorMessage(caught)); } finally { setBusy(false); } }
  return <DashboardShell><main className="mx-auto max-w-5xl p-5 md:p-8 lg:p-10"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#7c3aed]">Crypto settings</p><h1 className="mt-1 text-4xl font-black tracking-[-0.045em]">Solana wallet</h1><p className="mt-3 max-w-2xl text-[#6d6660]">Manage the encrypted devnet wallet used by Solana workflow actions. Your secret key never leaves the server.</p>{error && <div className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{!wallet ? <section className="mt-8 rounded-2xl border border-[#ddd3f5] bg-gradient-to-br from-[#f6f0ff] to-[#fff1fa] p-8"><h2 className="text-2xl font-black">Create your execution wallet</h2><p className="mt-2 max-w-lg text-sm leading-6 text-[#6d6660]">Create a dedicated devnet wallet to enable SOL transfers in your automations. Fund it with devnet SOL before publishing a transfer workflow.</p><button type="button" onClick={() => void createWallet()} disabled={busy} className="mt-6 rounded-xl bg-[#503eb6] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy ? "Creating…" : "Create Solana wallet"}</button></section> : <section className="mt-8 grid gap-5 md:grid-cols-[1.5fr_1fr]"><div className="rounded-2xl border border-[#e3ded8] bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-black">Wallet details</h2><span className="rounded-full bg-[#e3f8eb] px-3 py-1 text-xs font-bold text-[#168047]">{wallet.network}</span></div><p className="mt-6 text-xs font-bold uppercase tracking-[0.12em] text-[#8d8580]">Public address</p><div className="mt-2 break-all rounded-xl bg-[#f7f5f2] p-4 font-mono text-sm text-[#4c3b71]">{wallet.publicKey}</div><p className="mt-5 text-xs leading-5 text-[#6d6660]">Only this public address is displayed. The encrypted signing key is managed server-side.</p></div><div className="rounded-2xl border border-[#e3ded8] bg-white p-6"><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#8d8580]">Available balance</p><div className="mt-3 text-4xl font-black text-[#503eb6]">{wallet.balanceSol.toFixed(4)} <span className="text-lg">SOL</span></div><p className="mt-3 text-sm text-[#6d6660]">Devnet balance used for workflow transfers.</p><a href={`https://explorer.solana.com/address/${wallet.publicKey}?cluster=devnet`} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-lg border border-[#d8d1ca] px-4 py-2.5 text-sm font-bold hover:bg-[#f7f5f2]">View on Explorer ↗</a></div></section>}</main></DashboardShell>;
}
