CREATE TYPE "OrganizationRole" AS ENUM ('OWNER', 'ADMIN', 'EDITOR', 'VIEWER');

CREATE TABLE "Organization" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "owner_id" INTEGER NOT NULL, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "Organization_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OrganizationMember" ("id" TEXT NOT NULL, "organization_id" TEXT NOT NULL, "user_id" INTEGER NOT NULL, "role" "OrganizationRole" NOT NULL DEFAULT 'VIEWER', "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "OrganizationMember_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OrganizationInvitation" ("id" TEXT NOT NULL, "organization_id" TEXT NOT NULL, "email" TEXT NOT NULL, "role" "OrganizationRole" NOT NULL DEFAULT 'VIEWER', "token_hash" TEXT NOT NULL, "invited_by_id" INTEGER NOT NULL, "expires_at" TIMESTAMP(3) NOT NULL, "accepted_at" TIMESTAMP(3), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "OrganizationInvitation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditEvent" ("id" TEXT NOT NULL, "organization_id" TEXT NOT NULL, "actor_id" INTEGER, "action" TEXT NOT NULL, "resource_type" TEXT NOT NULL, "resource_id" TEXT, "metadata" JSONB NOT NULL DEFAULT '{}', "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PublishApproval" ("id" TEXT NOT NULL, "organization_id" TEXT NOT NULL, "zap_id" TEXT NOT NULL, "requested_by_id" INTEGER NOT NULL, "reviewed_by_id" INTEGER, "status" TEXT NOT NULL DEFAULT 'PENDING', "note" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "reviewed_at" TIMESTAMP(3), CONSTRAINT "PublishApproval_pkey" PRIMARY KEY ("id"));
ALTER TABLE "Zap" ADD COLUMN "organization_id" TEXT;
ALTER TABLE "AppConnection" ADD COLUMN "organization_id" TEXT;
CREATE UNIQUE INDEX "Organization_slug_key" ON "Organization"("slug");
CREATE UNIQUE INDEX "OrganizationMember_organization_id_user_id_key" ON "OrganizationMember"("organization_id", "user_id");
CREATE UNIQUE INDEX "OrganizationInvitation_token_hash_key" ON "OrganizationInvitation"("token_hash");
CREATE INDEX "Organization_owner_id_idx" ON "Organization"("owner_id");
CREATE INDEX "OrganizationMember_user_id_idx" ON "OrganizationMember"("user_id");
CREATE INDEX "OrganizationInvitation_email_expires_at_idx" ON "OrganizationInvitation"("email", "expires_at");
CREATE INDEX "AuditEvent_organization_id_created_at_idx" ON "AuditEvent"("organization_id", "created_at");
CREATE INDEX "PublishApproval_organization_id_status_created_at_idx" ON "PublishApproval"("organization_id", "status", "created_at");
CREATE INDEX "Zap_organization_id_status_updated_at_idx" ON "Zap"("organization_id", "status", "updated_at");
ALTER TABLE "Organization" ADD CONSTRAINT "Organization_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrganizationMember" ADD CONSTRAINT "OrganizationMember_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrganizationMember" ADD CONSTRAINT "OrganizationMember_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrganizationInvitation" ADD CONSTRAINT "OrganizationInvitation_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrganizationInvitation" ADD CONSTRAINT "OrganizationInvitation_invited_by_id_fkey" FOREIGN KEY ("invited_by_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PublishApproval" ADD CONSTRAINT "PublishApproval_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PublishApproval" ADD CONSTRAINT "PublishApproval_zap_id_fkey" FOREIGN KEY ("zap_id") REFERENCES "Zap"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PublishApproval" ADD CONSTRAINT "PublishApproval_requested_by_id_fkey" FOREIGN KEY ("requested_by_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PublishApproval" ADD CONSTRAINT "PublishApproval_reviewed_by_id_fkey" FOREIGN KEY ("reviewed_by_id") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Zap" ADD CONSTRAINT "Zap_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AppConnection" ADD CONSTRAINT "AppConnection_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
